name: 01 - Building Blocks
on: [workflow_dispatch]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failed steps
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodby
        run: |
          echo "Goodbye!"