name: 01 - Building Blocks
on: [workflow_dispatch]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Successful steps
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodby
        run: |
          echo "Goodbye!"